# ===============================
# Namespace
# ===============================
apiVersion: v1
kind: Namespace
metadata:
  name: infra-list
---
# ===============================
# PersistentVolumeClaim
# ===============================
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: link-dashboard-pvc
  namespace: infra-list
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 1Gi
---
# ===============================
# Deployment
# ===============================
apiVersion: apps/v1
kind: Deployment
metadata:
  name: link-dashboard
  namespace: infra-list
spec:
  replicas: 1
  selector:
    matchLabels:
      app: link-dashboard
  template:
    metadata:
      labels:
        app: link-dashboard
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      terminationGracePeriodSeconds: 10
      containers:
        - name: link-dashboard
          image: ghcr.io/khomsan146/allexcel:1.1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
          env:
            - name: DB_PATH
              value: /data/links.db
          volumeMounts:
            - name: data-volume
              mountPath: /data
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 256Mi
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 15
            periodSeconds: 20
          securityContext:
            runAsNonRoot: false
            allowPrivilegeEscalation: false
      volumes:
        - name: data-volume
          persistentVolumeClaim:
            claimName: link-dashboard-pvc
---
# ===============================
# Service
# ===============================
apiVersion: v1
kind: Service
metadata:
  name: link-dashboard-svc
  namespace: infra-list
spec:
  selector:
    app: link-dashboard
  ports:
    - name: http
      port: 80
      targetPort: 3000
---
# ===============================
# Ingress (Kong)
# ===============================
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: link-dashboard-ingress
  namespace: infra-list
  annotations:
    konghq.com/strip-path: 'true'
    kubernetes.io/ingress.class: kong
    konghq.com/protocols: 'https'
    konghq.com/https-redirect-status-code: '301'
    konghq.com/force-ssl-redirect: 'true'
spec:
  ingressClassName: kong
  rules:
    - host: monitorlist.tfac.or.th
      http:
        paths:
          - path:
            pathType: Prefix
            backend:
              service:
                name: link-dashboard-svc
                port:
                  number: 80
